# Generated by Django 4.2.7 on 2024-06-11 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0002_artist_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='covers/'),
        ),
    ]
