# Generated by Django 4.2.7 on 2024-06-11 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0003_artist_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='created_by',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
