# Generated by Django 4.2.7 on 2024-06-12 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0008_alter_music_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='creator',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='music',
            name='music_type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
