# Generated by Django 4.2.7 on 2024-06-12 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0009_alter_music_creator_alter_music_music_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='cover',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='music',
            name='content',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='music',
            name='cover',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
