# Generated by Django 4.2.7 on 2024-06-12 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0010_alter_artist_cover_alter_music_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='content',
        ),
        migrations.AddField(
            model_name='sample',
            name='album',
            field=models.ManyToManyField(related_name='album', to='musics.music'),
        ),
        migrations.AddField(
            model_name='sample',
            name='creator',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='sample',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
