# Generated by Django 4.2.7 on 2024-06-12 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0011_remove_music_content_sample_album_sample_creator_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='album',
        ),
        migrations.AddField(
            model_name='sample',
            name='album',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='musics.music'),
        ),
    ]
