# Generated by Django 4.2.7 on 2024-06-12 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0012_remove_sample_album_sample_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='album',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
