# Generated by Django 4.2.7 on 2024-06-13 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0013_alter_sample_album'),
    ]

    operations = [
        migrations.CreateModel(
            name='Melodiy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=100, null=True)),
                ('content', models.FileField(null=True, upload_to='melodies')),
            ],
        ),
        migrations.AlterModelOptions(
            name='artist',
            options={'ordering': ['-uploaded']},
        ),
        migrations.AddField(
            model_name='artist',
            name='uploaded',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
