# Generated by Django 4.2.7 on 2024-06-13 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0014_melodiy_alter_artist_options_artist_uploaded'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Melodiy',
            new_name='Melody',
        ),
    ]
